project_id = "isdfubjkhkyymtbkbgss"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.get-mapbox-key]
verify_jwt = false

[functions.send-business-enquiry]
verify_jwt = false

[functions.send-career-application]
verify_jwt = false

[functions.send-tour-request]
verify_jwt = false

[functions.admin-property-operations]
verify_jwt = false